# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RDO Compendium
email: ""
description: >-
  RDO Compendium is a bot that allows you to locate different types of collectibles, missions, herbs, animals, shops, treasures, and more within Red Dead Redemption 2 and Red Dead Online.

author:
    twitter: RDOCompendium
twitter:
  username: RDOCompendium
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og-logo.png
      height: 512
      width: 512
social:
  name: RDOCompendium
  links:
    - https://twitter.com/RDOCompendium
    - https://discord.gg/RBZVHQ7

# Google Analytics
google_analytics: UA-110509796-3

# Build settings
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - CNAME

compress_html:
  comments: ["<!-- ", " -->"]

support_link: https://discord.gg/RBZVHQ7
invite_link: https://discord.com/oauth2/authorize?client_id=721728527598354502&permissions=379968&scope=bot
patreon_link: https://www.patreon.com/bePatron?u=27626198